[package]
name = "atlaste_ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy_simple_text_input = "0.12"
encoding_rs = { workspace = true }
strum = { workspace = true }
url = { workspace = true }
rfd = "0.15"
