[workspace]
resolver = "2"
members = ["crates/*"]

[package]
name = "atlaste"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1
panic = "abort"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "fat"
panic = "abort"

[dependencies]
bevy = "0.15.3"
bevy_egui = "0.33.0"
rfd = "0.15.3"
thiserror = "2.0"

[dependencies.bevy_ecs_tilemap]
version = "0.15.0"
features = ["atlas"]

[dependencies.clap]
version = "4.5"
features = ["derive"]

[dependencies.lcf-rs]
path="./crates/lcf-rs"

[dependencies.log]
version = "*"
features = ["max_level_debug", "release_max_level_warn"]
