[package]
name = "atlaste_image"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
image = { version = "0.25.9", default-features = false, features = ["bmp"] }
png = "0.18.0"
thiserror = "2.0.17"
